#include <algorithm>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
using namespace std;

void solve(long long D, long long G, std::vector<long long> p,
           std::vector<long long> c) {}

// Generated by 2.11.0 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  long long D;
  std::scanf("%lld", &D);
  long long G;
  std::scanf("%lld", &G);
  std::vector<long long> p(D);
  std::vector<long long> c(D);
  for (int i = 0; i < D; i++) {
    std::scanf("%lld", &p[i]);
    std::scanf("%lld", &c[i]);
  }
  solve(D, G, std::move(p), std::move(c));
  return 0;
}
