#include <bits/stdc++.h>
using namespace std;

void solve(long long a, long long b, long long c, std::string s) {}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  // 整数の入力
  int a;
  cin >> a;
  // スペース区切りの整数の入力
  int b, c;
  cin >> b >> c;
  // 文字列の入力
  string s;
  cin >> s;
  // 出力
  cout << (a + b + c) << " " << s << endl;
  return 0;
}
