#include <bits/stdc++.h>
using namespace std;

const long long MOD = 998244353;

void solve(long long H, long long W, long long K, std::vector<long long> x, std::vector<long long> y){

}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long H;
    scanf("%lld",&H);
    long long W;
    scanf("%lld",&W);
    long long K;
    scanf("%lld",&K);
    std::vector<long long> x(2);
    std::vector<long long> y(2);
    for(int i = 0 ; i < 2 ; i++){
        scanf("%lld",&x[i]);
        scanf("%lld",&y[i]);
    }
    solve(H, W, K, std::move(x), std::move(y));
    return 0;
}
